import json

data = {"filetype": "picker_data", "version": 0.1,
        "charname": "mario_rig",
        "color_table": {"darkred": (0.6, 0.06, 0.01),
                        "yellow": (0.9, 0.7, 0.1),
                        "pink": (0.98, 0.58, 0.43),
                        "blue": (0.1, 0.4, 0.6),
                        "red": (0.8, 0.15, 0.15),
                        "black": (0, 0, 0)},
        "anim_table": {"kneeIK": "mario_rig:mario_ac_lf_kneeIK",
                    "lf_lowleg_bend": "mario_rig:mario_ac_lf_lowleg_bend",
                    "lf_upleg_bend": "mario_rig:mario_ac_lf_upleg_bend",
                    "rt_kneeIK": "mario_rig:mario_ac_rt_kneeIK",
                    "rt_lowleg_bend": "mario_rig:mario_ac_rt_lowleg_bend",
                    "rt_upleg_bend": "mario_rig:mario_ac_rt_upleg_bend",
                    "cn_midbody_bend": "mario_rig:mario_ac_cn_midbody_bend",
                    "cn_lowbody_bend": "mario_rig:mario_ac_cn_lowbody_bend",
                    "cn_topbody_bend": "mario_rig:mario_ac_cn_topbody_bend",
                    "cn_upperteeth": "mario_rig:mario_ac_cn_upperteeth",
                    "lf_eye": "mario_rig:mario_ac_lf_eye",
                    "rt_eye": "mario_rig:mario_ac_rt_eye",
                    "cn_nosetip": "mario_rig:mario_edit_cn_nosetip",
                    "cn_bottomhead": "mario_rig:mario_edit_cn_bottomhead",
                    "cn_middownhead": "mario_rig:mario_edit_cn_middownhead",
                    "cn_midnose": "mario_rig:mario_edit_cn_midnose",
                    "lf_ear": "mario_rig:mario_edit_lf_ear",
                    "rt_ear": "mario_rig:mario_edit_rt_ear",
                    "rt_eye": "mario_rig:mario_edit_rt_eye",
                    "cn_topnose": "mario_rig:mario_edit_cn_topnose",
                    "lf_eye": "mario_rig:mario_edit_lf_eye",
                    "cn_midtophead": "mario_rig:mario_edit_cn_midtophead",
                    "cn_tophead": "mario_rig:mario_edit_cn_tophead",
                    "cn_lowerteeth": "mario_rig:mario_ac_cn_lowerteeth",
                    "cn_tongue_5": "mario_rig:mario_ac_cn_tongue_5",
                    "cn_tongue_4": "mario_rig:mario_ac_cn_tongue_4",
                    "cn_tongue_3": "mario_rig:mario_ac_cn_tongue_3",
                    "cn_tongue_2": "mario_rig:mario_ac_cn_tongue_2",
                    "cn_tongue_1": "mario_rig:mario_ac_cn_tongue_1",
                    "lf_forearm_bend": "mario_rig:mario_ac_lf_forearm_bend",
                    "lf_arm_bend": "mario_rig:mario_ac_lf_arm_bend",
                    "rt_forearm_bend": "mario_rig:mario_ac_rt_forearm_bend",
                    "rt_arm_bend": "mario_rig:mario_ac_rt_arm_bend",
                    "lf_index3": "mario_rig:mario_ac_lf_index3",
                    "lf_index2": "mario_rig:mario_ac_lf_index2",
                    "lf_index1": "mario_rig:mario_ac_lf_index1",
                    "lf_index0": "mario_rig:mario_ac_lf_index0",
                    "lf_middle3": "mario_rig:mario_ac_lf_middle3",
                    "lf_middle2": "mario_rig:mario_ac_lf_middle2",
                    "lf_middle1": "mario_rig:mario_ac_lf_middle1",
                    "lf_middle0": "mario_rig:mario_ac_lf_middle0",
                    "lf_ring3": "mario_rig:mario_ac_lf_ring3",
                    "lf_ring2": "mario_rig:mario_ac_lf_ring2",
                    "lf_ring1": "mario_rig:mario_ac_lf_ring1",
                    "lf_ring0": "mario_rig:mario_ac_lf_ring0",
                    "lf_pinkey3": "mario_rig:mario_ac_lf_pinkey3",
                    "lf_pinkey2": "mario_rig:mario_ac_lf_pinkey2",
                    "lf_pinkey1": "mario_rig:mario_ac_lf_pinkey1",
                    "lf_pinkey0": "mario_rig:mario_ac_lf_pinkey0",
                    "lf_thumb3": "mario_rig:mario_ac_lf_thumb3",
                    "lf_thumb2": "mario_rig:mario_ac_lf_thumb2",
                    "lf_thumb1": "mario_rig:mario_ac_lf_thumb1",
                    "rt_index3": "mario_rig:mario_ac_rt_index3",
                    "rt_index2": "mario_rig:mario_ac_rt_index2",
                    "rt_index1": "mario_rig:mario_ac_rt_index1",
                    "rt_index0": "mario_rig:mario_ac_rt_index0",
                    "rt_middle3": "mario_rig:mario_ac_rt_middle3",
                    "rt_middle2": "mario_rig:mario_ac_rt_middle2",
                    "rt_middle1": "mario_rig:mario_ac_rt_middle1",
                    "rt_middle0": "mario_rig:mario_ac_rt_middle0",
                    "rt_ring3": "mario_rig:mario_ac_rt_ring3",
                    "rt_ring2": "mario_rig:mario_ac_rt_ring2",
                    "rt_ring1": "mario_rig:mario_ac_rt_ring1",
                    "rt_ring0": "mario_rig:mario_ac_rt_ring0",
                    "rt_pinkey3": "mario_rig:mario_ac_rt_pinkey3",
                    "rt_pinkey2": "mario_rig:mario_ac_rt_pinkey2",
                    "rt_pinkey1": "mario_rig:mario_ac_rt_pinkey1",
                    "rt_pinkey0": "mario_rig:mario_ac_rt_pinkey0",
                    "rt_thumb3": "mario_rig:mario_ac_rt_thumb3",
                    "rt_thumb2": "mario_rig:mario_ac_rt_thumb2",
                    "rt_thumb1": "mario_rig:mario_ac_rt_thumb1",
                    "lf_elbow_bend": "mario_rig:mario_ac_lf_elbow_bend",
                    "rt_elbow_bend": "mario_rig:mario_ac_rt_elbow_bend",
                    "lf_knee_bend": "mario_rig:mario_ac_lf_knee_bend",
                    "rt_knee_bend": "mario_rig:mario_ac_rt_knee_bend",
                    "cn_head": "mario_rig:mario_ac_cn_head",
                    "cn_neck": "mario_rig:mario_ac_cn_neck",
                    "cn_base": "mario_rig:mario_ac_cn_base",
                    "cn_spineFK1": "mario_rig:mario_ac_cn_spineFK1",
                    "cn_spineFK2": "mario_rig:mario_ac_cn_spineFK2",
                    "cn_pelvis": "mario_rig:mario_ac_cn_pelvis",
                    "cn_chest": "mario_rig:mario_ac_cn_chest",
                    "lf_clavicle": "mario_rig:mario_ac_lf_clavicle",
                    "rt_clavicle": "mario_rig:mario_ac_rt_clavicle",
                    "cn_upperbody": "mario_rig:mario_ac_cn_upperbody",
                    "lf_shoulderFK": "mario_rig:mario_ac_lf_shoulderFK",
                    "lf_elbowFK": "mario_rig:mario_ac_lf_elbowFK",
                    "lf_handFK": "mario_rig:mario_ac_lf_handFK",
                    "rt_shoulderFK": "mario_rig:mario_ac_rt_shoulderFK",
                    "rt_elbowFK": "mario_rig:mario_ac_rt_elbowFK",
                    "rt_handFK": "mario_rig:mario_ac_rt_handFK",
                    "lf_toe": "mario_rig:mario_ac_lf_toe",
                    "rt_toe": "mario_rig:mario_ac_rt_toe",
                    "lf_arm_settings": "mario_rig:mario_ac_lf_arm_settings",
                    "rt_arm_settings": "mario_rig:mario_ac_rt_arm_settings",
                    "lf_leg_settings": "mario_rig:mario_ac_lf_leg_settings",
                    "rt_leg_settings": "mario_rig:mario_ac_rt_leg_settings",
                    "lf_footIK": "mario_rig:mario_ac_lf_footIK",
                    "rt_footIK": "mario_rig:mario_ac_rt_footIK",
                    "lf_legPole": "mario_rig:mario_ac_lf_legPole",
                    "rt_legPole": "mario_rig:mario_ac_rt_legPole",
                    "cn_lookAt": "mario_rig:mario_ac_cn_lookAt",
                    "cn_jaw": "mario_rig:mario_ac_cn_jaw"},
        "selectors": ({"name": "Eyes", "color": "yellow",
                       "targets": ("cn_lookAt", )},
       {"name": "Head", "color": "yellow", "targets": ("cn_head", )},
            {"name": "Neck", "color": "yellow",
             "targets": ("cn_neck", )},
            {"name": "Chest", "color": "yellow",
             "targets": ("cn_chest", )},
            {"name": "SpineFK2", "color": "darkred",
             "targets": ("cn_spineFK2", )},
            {"name": "SpineFK1", "color": "darkred",
             "targets": ("cn_spineFK1", )},
            {"name": "Pelvis", "color": "yellow",
             "targets": ("cn_pelvis", )},
            {"name": "Upper Body", "color": "pink",
             "targets": ("cn_upperbody", )},
            {"name": "Clavicle Left", "color":
             "blue", "targets": ("lf_clavicle", )},
            {"name": "ShouldrFK Left", "color":
             "blue", "targets": ("lf_shoulderFK", )},
            {"name": "ElbowFK Left", "color":
             "blue", "targets": ("lf_elbowFK", )},
            {"name": "HandFK Left", "color":
                "blue", "targets": ("lf_handFK", )},
            {"name": "LegPole Left", "color":
             "blue", "targets": ("lf_legPole", )},
            {"name": "FootIK Left", "color":
                "blue", "targets": ("lf_footIK", )},
            {"name": "Clavicle Right", "color":
             "red", "targets": ("rt_clavicle", )},
            {"name": "ShouldrFK Right", "color":
             "red", "targets": ("rt_shoulderFK", )},
            {"name": "ElbowFK Right", "color":
             "red", "targets": ("rt_elbowFK", )},
            {"name": "HandFK Right", "color":
                "red", "targets": ("rt_handFK", )},
            {"name": "LegPole Right", "color":
             "red", "targets": ("rt_legPole", )},
            {"name": "FootIK Right", "color":
                "red", "targets": ("rt_footIK", )},
            {"name": "Base", "color": "pink", "targets": ("cn_base", )},
            {"name": "All", "color": "black",
             "targets": ("lf_kneeIK", "lf_lowleg_bend",
                         "lf_upleg_bend", "rt_kneeIK",
                         "rt_lowleg_bend", "rt_upleg_bend",
                         "cn_midbody_bend", "cn_lowbody_bend",
                         "cn_topbody_bend", "cn_upperteeth",
                         "lf_eye", "rt_eye", "cn_nosetip",
                                   "cn_bottomhead", "cn_middownhead",
                                   "cn_midnose", "lf_ear", "rt_ear",
                                   "rt_eye", "cn_topnose", "lf_eye",
                                   "cn_midtophead", "cn_tophead",
                                   "cn_lowerteeth", "cn_tongue_5",
                                   "cn_tongue_4", "cn_tongue_3",
                                   "cn_tongue_2", "cn_tongue_1",
                                   "lf_forearm_bend", "lf_arm_bend",
                                   "rt_forearm_bend", "rt_arm_bend",
                                   "lf_index3", "lf_index2", "lf_index1",
                                   "lf_index0", "lf_middle3", "lf_middle2",
                                   "lf_middle1", "lf_middle0", "lf_ring3",
                                   "lf_ring2", "lf_ring1", "lf_ring0",
                                   "lf_pinkey3", "lf_pinkey2", "lf_pinkey1",
                                   "lf_pinkey0", "lf_thumb3", "lf_thumb2",
                                   "lf_thumb1", "rt_index3", "rt_index2",
                                   "rt_index1", "rt_index0", "rt_middle3",
                                   "rt_middle2", "rt_middle1", "rt_middle0",
                                   "rt_ring3", "rt_ring2", "rt_ring1",
                                   "rt_ring0", "rt_pinkey3", "rt_pinkey2",
                                   "rt_pinkey1", "rt_pinkey0", "rt_thumb3",
                                   "rt_thumb2", "rt_thumb1", "lf_elbow_bend",
                                   "rt_elbow_bend", "lf_knee_bend",
                                   "rt_knee_bend", "cn_head",
                                   "cn_neck", "cn_base", "cn_spineFK1",
                                   "cn_spineFK2", "cn_pelvis", "cn_chest",
                                   "lf_clavicle", "rt_clavicle", "cn_upperbody",
                                   "lf_shoulderFK", "lf_elbowFK", "lf_handFK",
                                   "rt_shoulderFK", "rt_elbowFK", "rt_handFK",
                                   "lf_toe", "rt_toe", "lf_arm_settings",
                                   "rt_arm_settings", "lf_leg_settings",
                                   "rt_leg_settings", "lf_footIK",
                                   "rt_footIK", "lf_legPole",
                                   "rt_legPole", "cn_lookAt", "cn_jaw")})}

json_file = r"W:\dev\slides_picker\code\cmds\data.json"
with open(json_file, "w") as fp:
    json.dump(data, fp, indent=2, separators=[",", ":"])
