# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dummy.ui'
#
# Created: Fri May 16 15:32:04 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 630)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_all = QtGui.QPushButton(self.centralwidget)
        self.select_all.setGeometry(QtCore.QRect(10, 600, 370, 20))
        self.select_all.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(50, 50, 50);")
        self.select_all.setObjectName("select_all")
        self.rt_index0 = QtGui.QPushButton(self.centralwidget)
        self.rt_index0.setGeometry(QtCore.QRect(70, 290, 20, 20))
        self.rt_index0.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_index0.setObjectName("rt_index0")
        self.rt_index3 = QtGui.QPushButton(self.centralwidget)
        self.rt_index3.setGeometry(QtCore.QRect(70, 380, 20, 20))
        self.rt_index3.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_index3.setObjectName("rt_index3")
        self.lf_ring3 = QtGui.QPushButton(self.centralwidget)
        self.lf_ring3.setGeometry(QtCore.QRect(340, 380, 20, 20))
        self.lf_ring3.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_ring3.setObjectName("lf_ring3")
        self.rt_clavicle = QtGui.QPushButton(self.centralwidget)
        self.rt_clavicle.setGeometry(QtCore.QRect(150, 110, 45, 20))
        self.rt_clavicle.setStyleSheet("background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_clavicle.setObjectName("rt_clavicle")
        self.lf_ring1 = QtGui.QPushButton(self.centralwidget)
        self.lf_ring1.setGeometry(QtCore.QRect(340, 310, 20, 40))
        self.lf_ring1.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_ring1.setObjectName("lf_ring1")
        self.rt_middle2 = QtGui.QPushButton(self.centralwidget)
        self.rt_middle2.setGeometry(QtCore.QRect(50, 350, 20, 30))
        self.rt_middle2.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_middle2.setObjectName("rt_middle2")
        self.rt_leg_settings = QtGui.QPushButton(self.centralwidget)
        self.rt_leg_settings.setGeometry(QtCore.QRect(20, 550, 20, 20))
        self.rt_leg_settings.setStyleSheet("background-color: rgb(235, 48, 48);")
        self.rt_leg_settings.setObjectName("rt_leg_settings")
        self.rt_handFK = QtGui.QPushButton(self.centralwidget)
        self.rt_handFK.setGeometry(QtCore.QRect(10, 260, 80, 30))
        self.rt_handFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_handFK.setObjectName("rt_handFK")
        self.rt_shoulderFK = QtGui.QPushButton(self.centralwidget)
        self.rt_shoulderFK.setGeometry(QtCore.QRect(70, 110, 80, 40))
        self.rt_shoulderFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_shoulderFK.setObjectName("rt_shoulderFK")
        self.rt_footFK = QtGui.QPushButton(self.centralwidget)
        self.rt_footFK.setGeometry(QtCore.QRect(90, 530, 60, 40))
        self.rt_footFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_footFK.setObjectName("rt_footFK")
        self.cn_upperbody = QtGui.QPushButton(self.centralwidget)
        self.cn_upperbody.setGeometry(QtCore.QRect(150, 270, 90, 20))
        self.cn_upperbody.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.cn_upperbody.setObjectName("cn_upperbody")
        self.rt_toe = QtGui.QPushButton(self.centralwidget)
        self.rt_toe.setGeometry(QtCore.QRect(50, 530, 40, 40))
        self.rt_toe.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_toe.setObjectName("rt_toe")
        self.cn_base = QtGui.QPushButton(self.centralwidget)
        self.cn_base.setGeometry(QtCore.QRect(10, 580, 370, 20))
        self.cn_base.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.cn_base.setObjectName("cn_base")
        self.rt_handIK = QtGui.QPushButton(self.centralwidget)
        self.rt_handIK.setGeometry(QtCore.QRect(10, 230, 80, 30))
        self.rt_handIK.setStyleSheet("background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_handIK.setObjectName("rt_handIK")
        self.rt_index2 = QtGui.QPushButton(self.centralwidget)
        self.rt_index2.setGeometry(QtCore.QRect(70, 350, 20, 30))
        self.rt_index2.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_index2.setObjectName("rt_index2")
        self.lf_kneeFK = QtGui.QPushButton(self.centralwidget)
        self.lf_kneeFK.setGeometry(QtCore.QRect(200, 440, 40, 90))
        self.lf_kneeFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_kneeFK.setObjectName("lf_kneeFK")
        self.lf_middle2 = QtGui.QPushButton(self.centralwidget)
        self.lf_middle2.setGeometry(QtCore.QRect(320, 350, 20, 30))
        self.lf_middle2.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_middle2.setObjectName("lf_middle2")
        self.lf_middle3 = QtGui.QPushButton(self.centralwidget)
        self.lf_middle3.setGeometry(QtCore.QRect(320, 380, 20, 20))
        self.lf_middle3.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_middle3.setObjectName("lf_middle3")
        self.lf_pinkey2 = QtGui.QPushButton(self.centralwidget)
        self.lf_pinkey2.setGeometry(QtCore.QRect(360, 350, 20, 30))
        self.lf_pinkey2.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_pinkey2.setObjectName("lf_pinkey2")
        self.cn_chest = QtGui.QPushButton(self.centralwidget)
        self.cn_chest.setGeometry(QtCore.QRect(150, 130, 90, 20))
        self.cn_chest.setStyleSheet("background-color: rgb(240, 200, 40);")
        self.cn_chest.setObjectName("cn_chest")
        self.lf_knee_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_knee_bend.setGeometry(QtCore.QRect(240, 410, 20, 20))
        self.lf_knee_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_knee_bend.setObjectName("lf_knee_bend")
        self.lf_pinkey3 = QtGui.QPushButton(self.centralwidget)
        self.lf_pinkey3.setGeometry(QtCore.QRect(360, 380, 20, 20))
        self.lf_pinkey3.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_pinkey3.setObjectName("lf_pinkey3")
        self.lf_index2 = QtGui.QPushButton(self.centralwidget)
        self.lf_index2.setGeometry(QtCore.QRect(300, 350, 20, 30))
        self.lf_index2.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_index2.setObjectName("lf_index2")
        self.rt_thumb2 = QtGui.QPushButton(self.centralwidget)
        self.rt_thumb2.setGeometry(QtCore.QRect(90, 280, 20, 30))
        self.rt_thumb2.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_thumb2.setObjectName("rt_thumb2")
        self.lf_pinkey1 = QtGui.QPushButton(self.centralwidget)
        self.lf_pinkey1.setGeometry(QtCore.QRect(360, 310, 20, 40))
        self.lf_pinkey1.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_pinkey1.setObjectName("lf_pinkey1")
        self.rt_upleg_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_upleg_bend.setGeometry(QtCore.QRect(130, 340, 20, 20))
        self.rt_upleg_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_upleg_bend.setObjectName("rt_upleg_bend")
        self.lf_ring2 = QtGui.QPushButton(self.centralwidget)
        self.lf_ring2.setGeometry(QtCore.QRect(340, 350, 20, 30))
        self.lf_ring2.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_ring2.setObjectName("lf_ring2")
        self.rt_middle1 = QtGui.QPushButton(self.centralwidget)
        self.rt_middle1.setGeometry(QtCore.QRect(50, 310, 20, 40))
        self.rt_middle1.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_middle1.setObjectName("rt_middle1")
        self.lf_handIK = QtGui.QPushButton(self.centralwidget)
        self.lf_handIK.setGeometry(QtCore.QRect(300, 230, 80, 30))
        self.lf_handIK.setStyleSheet("background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.lf_handIK.setObjectName("lf_handIK")
        self.rt_footIK = QtGui.QPushButton(self.centralwidget)
        self.rt_footIK.setGeometry(QtCore.QRect(150, 530, 40, 40))
        self.rt_footIK.setStyleSheet("background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_footIK.setObjectName("rt_footIK")
        self.lf_index1 = QtGui.QPushButton(self.centralwidget)
        self.lf_index1.setGeometry(QtCore.QRect(300, 310, 20, 40))
        self.lf_index1.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_index1.setObjectName("lf_index1")
        self.lf_footFK = QtGui.QPushButton(self.centralwidget)
        self.lf_footFK.setGeometry(QtCore.QRect(240, 530, 60, 40))
        self.lf_footFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_footFK.setObjectName("lf_footFK")
        self.rt_arm_settings = QtGui.QPushButton(self.centralwidget)
        self.rt_arm_settings.setGeometry(QtCore.QRect(40, 410, 20, 20))
        self.rt_arm_settings.setStyleSheet("background-color: rgb(235, 48, 48);")
        self.rt_arm_settings.setObjectName("rt_arm_settings")
        self.cn_pelvis = QtGui.QPushButton(self.centralwidget)
        self.cn_pelvis.setGeometry(QtCore.QRect(150, 290, 90, 20))
        self.cn_pelvis.setStyleSheet("background-color: rgb(240, 200, 40);")
        self.cn_pelvis.setObjectName("cn_pelvis")
        self.lf_hipFK = QtGui.QPushButton(self.centralwidget)
        self.lf_hipFK.setGeometry(QtCore.QRect(200, 310, 40, 90))
        self.lf_hipFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_hipFK.setObjectName("lf_hipFK")
        self.rt_pinkey3 = QtGui.QPushButton(self.centralwidget)
        self.rt_pinkey3.setGeometry(QtCore.QRect(10, 380, 20, 20))
        self.rt_pinkey3.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_pinkey3.setObjectName("rt_pinkey3")
        self.rt_lowleg_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_lowleg_bend.setGeometry(QtCore.QRect(130, 480, 20, 20))
        self.rt_lowleg_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_lowleg_bend.setObjectName("rt_lowleg_bend")
        self.rt_thumb1 = QtGui.QPushButton(self.centralwidget)
        self.rt_thumb1.setGeometry(QtCore.QRect(90, 230, 20, 50))
        self.rt_thumb1.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_thumb1.setObjectName("rt_thumb1")
        self.lf_elbow_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_elbow_bend.setGeometry(QtCore.QRect(360, 90, 20, 20))
        self.lf_elbow_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_elbow_bend.setObjectName("lf_elbow_bend")
        self.cn_neck = QtGui.QPushButton(self.centralwidget)
        self.cn_neck.setGeometry(QtCore.QRect(180, 90, 30, 20))
        self.cn_neck.setStyleSheet("background-color: rgb(240, 200, 40);")
        self.cn_neck.setObjectName("cn_neck")
        self.lf_toe = QtGui.QPushButton(self.centralwidget)
        self.lf_toe.setGeometry(QtCore.QRect(300, 530, 40, 40))
        self.lf_toe.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_toe.setObjectName("lf_toe")
        self.cn_midbody_bend = QtGui.QPushButton(self.centralwidget)
        self.cn_midbody_bend.setGeometry(QtCore.QRect(240, 200, 20, 20))
        self.cn_midbody_bend.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.cn_midbody_bend.setObjectName("cn_midbody_bend")
        self.lf_leg_settings = QtGui.QPushButton(self.centralwidget)
        self.lf_leg_settings.setGeometry(QtCore.QRect(350, 550, 20, 20))
        self.lf_leg_settings.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_leg_settings.setObjectName("lf_leg_settings")
        self.cn_head = QtGui.QPushButton(self.centralwidget)
        self.cn_head.setGeometry(QtCore.QRect(160, 10, 70, 80))
        self.cn_head.setStyleSheet("background-color: rgb(240, 200, 40);")
        self.cn_head.setText("")
        self.cn_head.setObjectName("cn_head")
        self.lf_middle0 = QtGui.QPushButton(self.centralwidget)
        self.lf_middle0.setGeometry(QtCore.QRect(320, 290, 20, 20))
        self.lf_middle0.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_middle0.setObjectName("lf_middle0")
        self.rt_forearm_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_forearm_bend.setGeometry(QtCore.QRect(10, 180, 20, 20))
        self.rt_forearm_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_forearm_bend.setObjectName("rt_forearm_bend")
        self.rt_ring3 = QtGui.QPushButton(self.centralwidget)
        self.rt_ring3.setGeometry(QtCore.QRect(30, 380, 20, 20))
        self.rt_ring3.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_ring3.setObjectName("rt_ring3")
        self.rt_hipFK = QtGui.QPushButton(self.centralwidget)
        self.rt_hipFK.setGeometry(QtCore.QRect(150, 310, 40, 90))
        self.rt_hipFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_hipFK.setObjectName("rt_hipFK")
        self.rt_ring1 = QtGui.QPushButton(self.centralwidget)
        self.rt_ring1.setGeometry(QtCore.QRect(30, 310, 20, 40))
        self.rt_ring1.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_ring1.setObjectName("rt_ring1")
        self.lf_thumb2 = QtGui.QPushButton(self.centralwidget)
        self.lf_thumb2.setGeometry(QtCore.QRect(280, 280, 20, 30))
        self.lf_thumb2.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_thumb2.setObjectName("lf_thumb2")
        self.cn_spineFK2 = QtGui.QPushButton(self.centralwidget)
        self.cn_spineFK2.setGeometry(QtCore.QRect(150, 150, 90, 60))
        self.cn_spineFK2.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.cn_spineFK2.setObjectName("cn_spineFK2")
        self.rt_index1 = QtGui.QPushButton(self.centralwidget)
        self.rt_index1.setGeometry(QtCore.QRect(70, 310, 20, 40))
        self.rt_index1.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_index1.setObjectName("rt_index1")
        self.lf_armPole = QtGui.QPushButton(self.centralwidget)
        self.lf_armPole.setGeometry(QtCore.QRect(320, 110, 40, 40))
        self.lf_armPole.setStyleSheet("background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.lf_armPole.setObjectName("lf_armPole")
        self.rt_pinkey2 = QtGui.QPushButton(self.centralwidget)
        self.rt_pinkey2.setGeometry(QtCore.QRect(10, 350, 20, 30))
        self.rt_pinkey2.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_pinkey2.setObjectName("rt_pinkey2")
        self.lf_shoulderFK = QtGui.QPushButton(self.centralwidget)
        self.lf_shoulderFK.setGeometry(QtCore.QRect(240, 110, 80, 40))
        self.lf_shoulderFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_shoulderFK.setObjectName("lf_shoulderFK")
        self.rt_ring2 = QtGui.QPushButton(self.centralwidget)
        self.rt_ring2.setGeometry(QtCore.QRect(30, 350, 20, 30))
        self.rt_ring2.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_ring2.setObjectName("rt_ring2")
        self.rt_thumb3 = QtGui.QPushButton(self.centralwidget)
        self.rt_thumb3.setGeometry(QtCore.QRect(90, 310, 20, 30))
        self.rt_thumb3.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_thumb3.setObjectName("rt_thumb3")
        self.rt_middle0 = QtGui.QPushButton(self.centralwidget)
        self.rt_middle0.setGeometry(QtCore.QRect(50, 290, 20, 20))
        self.rt_middle0.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_middle0.setObjectName("rt_middle0")
        self.lf_kneeIK = QtGui.QPushButton(self.centralwidget)
        self.lf_kneeIK.setGeometry(QtCore.QRect(200, 400, 40, 40))
        self.lf_kneeIK.setStyleSheet("background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.lf_kneeIK.setObjectName("lf_kneeIK")
        self.cn_topbody_bend = QtGui.QPushButton(self.centralwidget)
        self.cn_topbody_bend.setGeometry(QtCore.QRect(240, 170, 20, 20))
        self.cn_topbody_bend.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.cn_topbody_bend.setObjectName("cn_topbody_bend")
        self.rt_middle3 = QtGui.QPushButton(self.centralwidget)
        self.rt_middle3.setGeometry(QtCore.QRect(50, 380, 20, 20))
        self.rt_middle3.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_middle3.setObjectName("rt_middle3")
        self.rt_elbowFK = QtGui.QPushButton(self.centralwidget)
        self.rt_elbowFK.setGeometry(QtCore.QRect(30, 150, 40, 80))
        self.rt_elbowFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_elbowFK.setObjectName("rt_elbowFK")
        self.lf_handFK = QtGui.QPushButton(self.centralwidget)
        self.lf_handFK.setGeometry(QtCore.QRect(300, 260, 80, 30))
        self.lf_handFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_handFK.setObjectName("lf_handFK")
        self.rt_pinkey0 = QtGui.QPushButton(self.centralwidget)
        self.rt_pinkey0.setGeometry(QtCore.QRect(10, 290, 20, 20))
        self.rt_pinkey0.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_pinkey0.setObjectName("rt_pinkey0")
        self.cn_lowbody_bend = QtGui.QPushButton(self.centralwidget)
        self.cn_lowbody_bend.setGeometry(QtCore.QRect(240, 230, 20, 20))
        self.cn_lowbody_bend.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.cn_lowbody_bend.setObjectName("cn_lowbody_bend")
        self.lf_clavicle = QtGui.QPushButton(self.centralwidget)
        self.lf_clavicle.setGeometry(QtCore.QRect(195, 110, 45, 20))
        self.lf_clavicle.setStyleSheet("background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.lf_clavicle.setObjectName("lf_clavicle")
        self.lf_index3 = QtGui.QPushButton(self.centralwidget)
        self.lf_index3.setGeometry(QtCore.QRect(300, 380, 20, 20))
        self.lf_index3.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_index3.setObjectName("lf_index3")
        self.rt_kneeFK = QtGui.QPushButton(self.centralwidget)
        self.rt_kneeFK.setGeometry(QtCore.QRect(150, 440, 40, 90))
        self.rt_kneeFK.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_kneeFK.setObjectName("rt_kneeFK")
        self.rt_kneeIK = QtGui.QPushButton(self.centralwidget)
        self.rt_kneeIK.setGeometry(QtCore.QRect(150, 400, 40, 40))
        self.rt_kneeIK.setStyleSheet("background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_kneeIK.setObjectName("rt_kneeIK")
        self.lf_index0 = QtGui.QPushButton(self.centralwidget)
        self.lf_index0.setGeometry(QtCore.QRect(300, 290, 20, 20))
        self.lf_index0.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_index0.setObjectName("lf_index0")
        self.lf_pinkey0 = QtGui.QPushButton(self.centralwidget)
        self.lf_pinkey0.setGeometry(QtCore.QRect(360, 290, 20, 20))
        self.lf_pinkey0.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_pinkey0.setObjectName("lf_pinkey0")
        self.cn_spineFK1 = QtGui.QPushButton(self.centralwidget)
        self.cn_spineFK1.setGeometry(QtCore.QRect(150, 210, 90, 60))
        self.cn_spineFK1.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.cn_spineFK1.setObjectName("cn_spineFK1")
        self.lf_forearm_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_forearm_bend.setGeometry(QtCore.QRect(360, 170, 20, 20))
        self.lf_forearm_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_forearm_bend.setObjectName("lf_forearm_bend")
        self.rt_pinkey1 = QtGui.QPushButton(self.centralwidget)
        self.rt_pinkey1.setGeometry(QtCore.QRect(10, 310, 20, 40))
        self.rt_pinkey1.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_pinkey1.setObjectName("rt_pinkey1")
        self.lf_arm_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_arm_bend.setGeometry(QtCore.QRect(270, 90, 20, 20))
        self.lf_arm_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_arm_bend.setObjectName("lf_arm_bend")
        self.rt_elbow_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_elbow_bend.setGeometry(QtCore.QRect(10, 90, 20, 20))
        self.rt_elbow_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_elbow_bend.setObjectName("rt_elbow_bend")
        self.rt_ring0 = QtGui.QPushButton(self.centralwidget)
        self.rt_ring0.setGeometry(QtCore.QRect(30, 290, 20, 20))
        self.rt_ring0.setStyleSheet("background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_ring0.setObjectName("rt_ring0")
        self.lf_elbowFK = QtGui.QPushButton(self.centralwidget)
        self.lf_elbowFK.setGeometry(QtCore.QRect(320, 140, 40, 90))
        self.lf_elbowFK.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_elbowFK.setObjectName("lf_elbowFK")
        self.lf_thumb3 = QtGui.QPushButton(self.centralwidget)
        self.lf_thumb3.setGeometry(QtCore.QRect(280, 310, 20, 30))
        self.lf_thumb3.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_thumb3.setObjectName("lf_thumb3")
        self.lf_upleg_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_upleg_bend.setGeometry(QtCore.QRect(240, 340, 20, 20))
        self.lf_upleg_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_upleg_bend.setObjectName("lf_upleg_bend")
        self.lf_ring0 = QtGui.QPushButton(self.centralwidget)
        self.lf_ring0.setGeometry(QtCore.QRect(340, 290, 20, 20))
        self.lf_ring0.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_ring0.setObjectName("lf_ring0")
        self.lf_lowleg_bend = QtGui.QPushButton(self.centralwidget)
        self.lf_lowleg_bend.setGeometry(QtCore.QRect(240, 480, 20, 20))
        self.lf_lowleg_bend.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lf_lowleg_bend.setObjectName("lf_lowleg_bend")
        self.rt_arm_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_arm_bend.setGeometry(QtCore.QRect(100, 90, 20, 20))
        self.rt_arm_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_arm_bend.setObjectName("rt_arm_bend")
        self.lf_middle1 = QtGui.QPushButton(self.centralwidget)
        self.lf_middle1.setGeometry(QtCore.QRect(320, 310, 20, 40))
        self.lf_middle1.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_middle1.setObjectName("lf_middle1")
        self.lf_footIK = QtGui.QPushButton(self.centralwidget)
        self.lf_footIK.setGeometry(QtCore.QRect(200, 530, 40, 40))
        self.lf_footIK.setStyleSheet("background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.lf_footIK.setObjectName("lf_footIK")
        self.rt_armPole = QtGui.QPushButton(self.centralwidget)
        self.rt_armPole.setGeometry(QtCore.QRect(30, 110, 40, 40))
        self.rt_armPole.setStyleSheet("background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.rt_armPole.setObjectName("rt_armPole")
        self.lf_arm_settings = QtGui.QPushButton(self.centralwidget)
        self.lf_arm_settings.setGeometry(QtCore.QRect(330, 410, 20, 20))
        self.lf_arm_settings.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_arm_settings.setObjectName("lf_arm_settings")
        self.rt_knee_bend = QtGui.QPushButton(self.centralwidget)
        self.rt_knee_bend.setGeometry(QtCore.QRect(130, 410, 20, 20))
        self.rt_knee_bend.setStyleSheet("background-color: rgb(170, 25, 25);")
        self.rt_knee_bend.setObjectName("rt_knee_bend")
        self.lf_thumb1 = QtGui.QPushButton(self.centralwidget)
        self.lf_thumb1.setGeometry(QtCore.QRect(280, 230, 20, 50))
        self.lf_thumb1.setStyleSheet("background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.lf_thumb1.setObjectName("lf_thumb1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CharacterPicker", None, QtGui.QApplication.UnicodeUTF8))
        self.select_all.setText(QtGui.QApplication.translate("MainWindow", "SELECT ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.rt_handIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.lf_handIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.rt_footIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.lf_armPole.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.lf_kneeIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.rt_kneeIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.lf_footIK.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.rt_armPole.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))

